try {
	local a = 1;
	local b = a(2);
} catch (Exception e) {
	print(e:message);
} finally {
	print('Finally!');
}