
class Exc1 {
}

class Exc2 {
}

function inner() {
	throw Exception("boo!");
}

try {
	try {
		local a = 5;
		local b = a + 1;
		inner();
		#throw Exc1();
		print("No boo");
	} catch (Exception e) {
		print(e:message);
		print(e:stacktrace);
		throw Exc2();
	}
	print("after catch exc");
} catch (Exc1 e) {
	print("caught exc1");
} catch (Exc2) {
	print("caught exc2");
}

try {
	# 1
	local x = 10;
	while (x > 0) {
		try {
			# 2
			if (x = 5)
				break;
			throw Exception('Ex1');
		} catch (Exception e) {
			print('x2:', e:message);
		}
		x -= 1;
	}
	# 1
	throw Exception('Ex2');
} catch (Exception e) {
	print('x1:', e:message);
}

throw Exc1();
print("after catch exc1");